name: mockup-terraform-plan-on-pull-request

on:
  pull_request:
    branches:
      - main
    paths:
      - dummy/terraform/**/*

env:
  OPERATION: plan

jobs:
  get_targets:
    runs-on: ubuntu-latest

    outputs:
      operation: ${{ env.OPERATION }}
      targets: ${{ steps.targets.outputs.targets }}

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          clean: false

      - name: get git diff files as list
        id: changed-files
        uses: tj-actions/changed-files@v36

      - name: organize and convert diff list to json
        id: targets
        run: |
          bash ./bin/get_tf_targets.sh ${{ steps.changed-files.outputs.all_changed_files }}

  # envのスコープはjobs内までなので、jobs側のoutputsで定義して引き回す必要がある
  call_reusable_terraform:
    name: do terraform ${{ needs.get_targets.outputs.targets.operation }}
    needs: get_targets
    uses: kaz-under-the-bridge/github-actions-playground/.github/workflows/_reusable_terraform.yaml@main
    with:
      operation: ${{ needs.get_targets.outputs.targets.operation }}
      targets: ${{ needs.get_targets.outputs.targets }}
